Repository daeuniverse/dae-bot, pull requests merged in 2023-06, with the labels that each got.

#2 refactor(handler): rework tg client
  README.md
  api/mock/telegram.ts
  mock/async_test.js
  src/constant.ts
  src/telegram.ts
Labels: refactor

#3 patch(handler): prevent stargazer listner from ddos
  .enc.env
  package-lock.json
  package.json
  src/index.ts
Labels: patch

#5 feat(handler/push): add push.daed-sync-upstream handler
  src/index.ts
Labels: feature

#6 patch(handler/push.dae-sync-upstream): fix async await broken logic
  src/index.ts
Labels: feature

#7 feat(pull_request.synchronize): add branch-up-to-date handler
  .enc.env
  fixtures/pull_request.synchronize.json
  package-lock.json
  package.json
  src/index.ts
Labels: feature

#8 feat(pull_request.opened): add label-attacher
  fixtures/pull_request.opened.json
  src/index.ts
Labels: feature

#10 patch(label-attach): handle feat -> feature
  src/index.ts
Labels: feature, patch

#11 feat(pull_request): add pr-merge handler
  package-lock.json
  package.json
  src/index.ts
Labels: feature

#12 patch(pr.merged): apply minior patches
  src/index.ts
Labels: patch

#13 chore: apply some code quality fixes
  src/handler.ts
  src/index.ts
  src/telegram.ts
Labels: fix, chore

#14 ci: add default deploy workflow
  .github/workflows/deploy.yml
Labels: ci

#15 fix: incorrect label gets added
  src/index.ts
Labels: fix

#16 refactor: rework sync-upstream event handler
  fixtures/create.branch.json
  src/index.ts
Labels: refactor

#18 chore: add codeowners
  CODEOWNERS
Labels: chore

#17 feat(handler): add auto-release event handler
  fixtures/issue_comment.created.json
  mock/re_test.ts
  src/index.ts
Labels: feature

#19 patch(release-automation-handler): trigger event ONLY when issue.state == 'closed'
  fixtures/issues.closed.json
  src/index.ts
Labels: patch

#20 feat: add release creation handler
  fixtures/release.created.json
  fixtures/release.published.json
  fixtures/release.released.json
  src/index.ts
Labels: feature

#21 refactor: rework star.created event handler
  src/common.ts
  src/config.ts
  src/events/star.created.ts
  src/index.ts
  src/runner.ts
  src/telegram.ts
Labels: refactor

#22 refactor: rework pull_request.opened event handler
  src/config.ts
  src/events/pull_request.opened.ts
  src/index.ts
Labels: refactor

#23 refactor: rework pull_request.closed event handler
  src/config.ts
  src/events/pull_request.closed.ts
  src/events/star.created.ts
  src/index.ts
Labels: refactor

#24 refactor: rework issue event handler
  src/config.ts
  src/events/issue.closed.ts
  src/events/issues.closed.ts
  src/events/issues.opened.ts
  src/index.ts
Labels: refactor

#25 refactor: rework pull_request.synchronize event handler
  src/config.ts
  src/events/pull_request.syncronize.ts
  src/index.ts
Labels: refactor

#26 refactor: rework issue_comment.created event handler
  src/config.ts
  src/events/issue_comment.created.ts
  src/index.ts
Labels: refactor

#27 refactor: rework event listener and runner
  src/index.ts
Labels: refactor

#28 feat: add pull_request.labeled handler
  fixtures/pull_request.labeled.json
  src/config.ts
  src/events/pull_request.closed.ts
  src/events/pull_request.labeled.ts
  src/events/pull_request.opened.ts
  src/events/pull_request.syncronize.ts
  src/index.ts
Labels: feature

#29 feat(pr.opened): add filter to determine if "not-yet-tested" is eligible
  src/events/pull_request.closed.ts
  src/events/pull_request.opened.ts
  src/events/pull_request.syncronize.ts
Labels: feature

#30 patch(handler/pull_request): add pr title to default msg
  src/events/pull_request.closed.ts
  src/events/pull_request.syncronize.ts
Labels: patch, not-yet-tested

#36 patch(release.trigger): mod release.released -> release.published
  src/events/release.released.ts
  src/index.ts
Labels: patch

#38 fix(pr.opened): fix broken request-pr-review step
  mock/pr_review_request_test.ts
  package-lock.json
  package.json
  src/events/pull_request.opened.ts
Labels: patch

#39 feat(instrument): add tracing support with otel
  .enc.env
  package.json
  src/index.ts
  src/trace.ts
Labels: feature

#42 feat(handler/push): add instrumentation
  api/mock/telegram.ts
  mock/telegram_test.ts
  src/events/push.ts
  src/index.ts
  src/runner.ts
  src/telegram.ts
  src/trace.ts
Labels: feature, not-yet-tested

#44 feat(handler/star.created): add tracing support
  src/events/push.ts
  src/events/star.created.ts
Labels: feature, ci, not-yet-tested

#47 fixture(mock): add error-handling and simple-tracer examples
  mock/basic_tracer_node.ts
  mock/error_handling_test.ts
  package-lock.json
  package.json
  src/index.ts
  src/trace.ts
Labels: fix, tested, fixture

#48 fix(handler/pr.opened): handle "fixture" label
  src/events/pull_request.opened.ts
Labels: fix, tested

#49 hotfix(handler/push): fix fix,fixture label conflict issue
  src/events/pull_request.opened.ts
Labels: fix

#50 refactor(handler/push): add default span and error handling
  src/events/push.ts
Labels: refactor, tested

#51 feat(handler/pr.close): add tracing functionality
  src/events/pull_request.closed.ts
  src/events/push.ts
Labels: feature, not-yet-tested

#52 fix(handler/pr.opened/label): fix,fixture label conflict
  mock/label_filter_test.ts
  src/events/pull_request.opened.ts
Labels: fix, tested
