Repository daeuniverse/dae-bot, pull requests merged in 2023-07, with the labels that each got.

#53 refactor(star.created,pr.closed): refine tracing
  src/events/pull_request.closed.ts
  src/events/star.created.ts
Labels: refactor, not-yet-tested

#54 refactor(handler/pr.opened): add tracing support
  mock/template/span.ts
  src/events/pull_request.closed.ts
  src/events/pull_request.opened.ts
  src/events/push.ts
  src/events/star.created.ts
Labels: refactor, tested

#55 refactor(handler/pr.labeled): add tracing support
  src/constant.ts
  src/events/pull_request.labeled.ts
  src/events/pull_request.opened.ts
Labels: refactor, tested

#56 optimize(release-gate): add condition to improve auto release
  src/events/issue_comment.created.ts
  src/events/pull_request.closed.ts
Labels: tested, optimize

#57 refactor(handler/release.published): add tracing support
  src/config.ts
  src/events/release.published.ts
  src/events/release.released.ts
Labels: refactor, tested

#58 refactor(handler/issues.closed): add tracing support
  src/events/issue.closed.ts
  src/events/issues.closed.ts
Labels: refactor, tested

#59 refactor(handler/issues.opened): add tracing support
  src/events/issues.opened.ts
Labels: refactor, tested

#61 hotfix(pr.synchronized): rework merge head branch logic
  src/events/pull_request.syncronize.ts
Labels: fix

#62 feat(sync_upstream): add auto-merge support
  mock/delete_remote_branch_test.ts
  src/events/pull_request.opened.ts
  src/events/push.ts
Labels: feature, tested

#64 fixture(mock) add pr_add_assignee test
  mock/pr_add_assignee_test.ts
  src/events/push.ts
Labels: fixture

#65 chore: add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#66 fix(default_labels): re-arrange order
  src/constant.ts
Labels: fix

#67 feat(sync-upstream): include dae-wing as a sync candidate
  mock/pr_merge_test.ts
  mock/ref_delete_test.ts
  src/events/push.ts
Labels: feature, tested

#68 fix(push/sync-upstream): fix broken logic; disable auto_merge
  src/events/push.ts
Labels: fix, tested

#69 fixture(mock): add pr_list_check_suite_test
  fixtures/branch.created.json
  fixtures/checks.list_check_suites.json
  mock/pr_list_check_suite_test.ts
Labels: not-yet-tested, fixture

#72 chore: prepare for sync-upstream event chain
  mock/update_sync_pr_test.ts
  src/events/pull_request.closed.ts
  src/events/push.ts
Labels: chore

#75 hotfix(pr.closed.release): publish release based on tag ref not HEAD
  src/events/pull_request.closed.ts
Labels: fix

#74 feat: add workflow_run.completed handler
  fixtures/workflow_run.completed.json
  mock/pr_list_test.ts
  mock/update_sync_pr_test.ts
  src/config.ts
  src/events/push.ts
  src/events/workflow_run.completed.ts
  src/gateway.ts
  src/index.ts
Labels: feature, tested

#77 patch(gateway): add additional check_run event filter
  src/gateway.ts
Labels: patch

#78 patch(check_run.completed): general refinement
  src/config.ts
  src/events/check_run.completed.ts
  src/events/event_template.ts
  src/events/workflow_run.completed.ts
  src/gateway.ts
  src/index.ts
  src/runner.ts
Labels: patch, tested

#79 ci/chore: get rid of Dockerfile (not needed)
  Dockerfile
Labels: chore, ci

#80 refactor(mock): rename async_test.js -> async_test.ts
  mock/async_test.js
  mock/async_test.ts
Labels: refactor, fixture

#81 hotfix(push/sync_upstream): fix broken logic
  src/events/push.ts
Labels: fix

#82 feat/refactor(pr.opened): parse multiple labels
  mock/label_filter_test.ts
  src/constant.ts
  src/events/pull_request.opened.ts
Labels: feature, refactor, tested

#83 hotfix(workflow_run.completed/sync_context): fix undefined context
  src/events/workflow_run.completed.ts
Labels: not-yet-tested, hotfix

#84 fixture(mock): add ref test
  mock/get_ref_test.ts
Labels: fixture

#86 ci: enable multi-env deployment
  .enc.env
  .github/workflows/deploy.yml
Labels: ci

#85 feat(issue_comment.created): apply markdown formatting with prettier.format
  package-lock.json
  package.json
  src/events/issue_comment.created.ts
Labels: feature

#87 refactor: persist releaseCandidates in constant.ts
  src/constant.ts
  src/events/issue_comment.created.ts
Labels: refactor, tested
